package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.DockerSupportFeature
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.dockerSupport
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'PullRequestBuildType'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("PullRequestBuildType")) {
    features {
        val feature1 = find<DockerSupportFeature> {
            dockerSupport {
                loginToRegistry = on {
                    dockerRegistryId = "PROJECT_EXT_33"
                }
            }
        }
        feature1.apply {
            loginToRegistry = on {
                dockerRegistryId = "PROJECT_EXT_200"
            }
        }
    }
}
