package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.GradleBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'PullRequestBuildType'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("PullRequestBuildType")) {
    expectSteps {
        gradle {
            name = "Run help task"
            tasks = "help"
            useGradleWrapper = true
            dockerImage = "mobile-docker-common.artifactory.xero-support.com/android-build-agent:0.0.3.5"
        }
    }
    steps {
        update<GradleBuildStep>(0) {
            clearConditions()
            dockerPull = true
            param("org.jfrog.artifactory.selectedDeployableServer.defaultModuleVersionConfiguration", "GLOBAL")
        }
    }
}
